name: Build and Deploy

on:
  push:
    branches: [master]
    paths-ignore: ['.github/**', 'README.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  # deploy:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Configure AWS Credentials
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-1
  #   - name: Deploy
  #     run: |
  #       sudo curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
  #       sudo chmod +x /usr/local/bin/copilot
  #       copilot app ls
  #       copilot env show
  #       copilot svc deploy -n my-api --env test